development:
  adapter: postgresql
  encoding: unicode
  database: minesweeper_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: minesweeper_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: minesweeper_production
  pool: 5
